export const ratingList = [
  {
    id: 1,
    value: "1",
    label: "1🌟",
  },
  {
    id: 2,
    value: "2",
    label: "2🌟",
  },
  {
    id: 3,
    value: "3",
    label: "3🌟",
  },
  {
    id: 4,
    value: "4",
    label: "4🌟",
  },
  {
    id: 5,
    value: "5",
    label: "5🌟",
  },
];

export const dataList = [
  {
    id: 1,
    location: "San Miguel de Allende, Mexico",
    title: "lounge resort",
    serviceTime: 4,
    deliveryFee: "2226 Lorem ipsum dolor sit.",
    category: "place",
    cuisine: "american",
    rating: 5,
    price: 2500,
    coverSrc: "/images/places/ameri.jpg",
    date: "2022-08-26",
    type: "Houses",
  },
  {
    // location: '',
    id: 2,
    location: "Udaipur, India",
    title: "door urban",
    serviceTime: 14,
    deliveryFee: "6323 Lorem ipsum dolor sit.",
    category: "place",
    cuisine: "italian",
    rating: 4,
    price: 1000,
    coverSrc: "/images/places/italian.webp",
    date: "2022-08-06",
    type: "Hotels",
  },
  {
    id: 3,
    location: "Istanbul",
    title: "chow",
    serviceTime: 25,
    deliveryFee: "663 Lorem ipsum dolor sit.",
    category: "place",
    cuisine: "chinese",
    rating: 3,
    price: 2000,
    coverSrc: "/images/places/china.jpg",
    date: "2022-08-07",
    type: "Restaurants",
  },
  {
    id: 4,
    location: "Ubud, Indonesia",
    title: "wharf seafood",
    serviceTime: 36,
    deliveryFee: "46466 Lorem ipsum dolor sit.",
    category: "place",
    cuisine: "american",
    rating: 1,
    price: 1800,
    coverSrc: "/images/places/sea.jpg",
    date: "2022-08-08",
    type: "Restaurants",
  },
  {
    id: 5,
    location: "Kyoto, Japan",
    title: "Tossin",
    serviceTime: 25,
    deliveryFee: "646 Lorem ipsum dolor sit.",
    category: "place",
    cuisine: "italian",
    rating: 5,
    price: 2000,
    coverSrc: "/images/places/italiian.jpg",
    date: "2022-08-09",
    type: "Restaurants",
  },
  {
    id: 6,
    location: "Florence",
    title: "stories noodles",
    serviceTime: 26,
    deliveryFee: "4774 Lorem ipsum dolor sit.",
    category: "place",
    cuisine: "chinese",
    rating: 5,
    price: 3500,
    coverSrc: "/images/places/fookyew2.jpg",
    date: "2022-08-10",
    type: "Houses",
  },
  {
    id: 7,
    location: "Mexico City",
    title: "Nacho cheeseburger",
    serviceTime: 2,
    deliveryFee: "747 Lorem ipsum dolor sit.",
    category: "dish",
    cuisine: "american",
    rating: 2,
    price: 2200,
    coverSrc: "/images/places/Lilac-Cottage.jpg",
    date: "2022-08-11",
    type: "Hotels",
  },
  {
    id: 8,
    location: "Oaxaca, Mexico",
    title: "Mushroom Risotto",
    serviceTime: 15,
    deliveryFee: "474 Lorem ipsum dolor sit.",
    category: "dish",
    cuisine: "italian",
    rating: 1,
    price: 1900,
    coverSrc: "/images/places/Lakeside.jpg",
    date: "2022-08-12",
    type: "Restaurants",
  },
  {
    id: 9,
    location: "Chiang Mai, Thailand",
    title: "Meadow View",
    serviceTime: 18,
    deliveryFee: "374 Lorem ipsum dolor sit.",
    category: "dish",
    cuisine: "chinese",
    rating: 4,
    price: 2750,
    coverSrc: "/images/places/Meadow-View.jpg",
    date: "2022-09-06",
    type: "Houses",
  },
  {
    id: 10,
    location: "Bangkok",
    title: "Orchard House",
    serviceTime: 6,
    deliveryFee: "4848 Lorem ipsum dolor sit.",
    category: "dish",
    cuisine: "american",
    rating: 2,
    price: 4350,
    coverSrc: "/images/places/Orchard-House.jpg",
    date: "2022-09-02",
    type: "Hotels",
  },
  {
    id: 11,
    location: "Taipei",
    title: "Springfield",
    serviceTime: 8,
    deliveryFee: "4848 Lorem ipsum dolor sit.",
    category: "dish",
    cuisine: "italian",
    rating: 3,
    price: 3300,
    coverSrc: "/images/places/Springfield.jpg",
    date: "2022-08-25",
    type: "Hotels",
  },
  {
    id: 12,
    location: "Kraków, Poland",
    title: "The Old Post Office",
    serviceTime: 12,
    deliveryFee: "4747 Lorem ipsum dolor sit.",
    category: "dish",
    cuisine: "chinese",
    rating: 2,
    price: 4100,
    coverSrc: "/images/places/The-Old-Post-Office.jpg",
    date: "2022-10-12",
    type: "Houses",
  },
  {
    id: 13,
    location: "San Miguel de Allende, Mexico",
    title: "The Old Vicarage",
    serviceTime: 9,
    deliveryFee: "4748 Lorem ipsum dolor sit.",
    category: "place",
    cuisine: "american",
    rating: 5,
    price: 2500,
    coverSrc: "/images/places/The-Old-Vicarage.jpg",
    date: "2022-08-26",
    type: "Houses",
  },
  {
    // location: '',
    id: 14,
    location: "Udaipur, India",
    title: "Winterfell House",
    serviceTime: 6,
    deliveryFee: "84848 Lorem ipsum dolor sit.",
    category: "place",
    cuisine: "italian",
    rating: 4,
    price: 1000,
    coverSrc: "/images/places/Winterfell-House.jpg",
    date: "2022-08-06",
    type: "Hotels",
  },
  {
    id: 15,
    location: "Istanbul",
    title: "Beeches",
    serviceTime: 2,
    deliveryFee: "3838 Lorem ipsum dolor sit.",
    category: "place",
    cuisine: "chinese",
    rating: 3,
    price: 2000,
    coverSrc: "/images/places/Beeches.jpg",
    date: "2022-08-07",
    type: "Restaurants",
  },
  {
    id: 16,
    location: "Ubud, Indonesia",
    title: "Binyamin mellish",
    serviceTime: 3,
    deliveryFee: "3377 Lorem ipsum dolor sit.",
    category: "place",
    cuisine: "american",
    rating: 1,
    price: 1800,
    coverSrc: "/images/places/Binyamin-mellish.jpg",
    date: "2022-08-08",
    type: "Restaurants",
  },
  {
    id: 17,
    location: "Kyoto, Japan",
    title: "Fairview",
    serviceTime: 7,
    deliveryFee: "3734 Lorem ipsum dolor sit.",
    category: "place",
    cuisine: "italian",
    rating: 5,
    price: 2000,
    coverSrc: "/images/places/Fairview.jpg",
    date: "2022-08-09",
    type: "Restaurants",
  },
  {
    id: 18,
    location: "Florence",
    title: "Haven",
    serviceTime: 4,
    deliveryFee: "8943 Lorem ipsum dolor sit.",
    category: "place",
    cuisine: "chinese",
    rating: 5,
    price: 3500,
    coverSrc: "/images/places/Haven.jpg",
    date: "2022-08-10",
    type: "Houses",
  },
  {
    id: 19,
    location: "Mexico City",
    title: "Highclere",
    serviceTime: 3,
    deliveryFee: "4740 Lorem ipsum dolor sit.",
    category: "dish",
    cuisine: "american",
    rating: 2,
    price: 2200,
    coverSrc: "/images/places/Highclere.jpg",
    date: "2022-08-11",
    type: "Hotels",
  },
  {
    id: 20,
    location: "Oaxaca, Mexico",
    title: "Binyamin-mellish-2",
    serviceTime: 8,
    deliveryFee: "4577 Lorem ipsum dolor sit.",
    category: "dish",
    cuisine: "italian",
    rating: 1,
    price: 1900,
    coverSrc: "/images/places/Binyamin-mellish-2.jpg",
    date: "2022-08-12",
    type: "Restaurants",
  },
  {
    id: 21,
    location: "Chiang Mai, Thailand",
    title: "Ivy-House",
    serviceTime: 9,
    deliveryFee: "4848 Lorem ipsum dolor sit.",
    category: "dish",
    cuisine: "chinese",
    rating: 4,
    price: 2750,
    coverSrc: "/images/places/Ivy-House.jpg",
    date: "2022-09-06",
    type: "Houses",
  },
  {
    id: 22,
    location: "Bangkok",
    title: "Meadow View",
    serviceTime: 9,
    deliveryFee: "885 Lorem ipsum dolor sit.",
    category: "dish",
    cuisine: "american",
    rating: 2,
    price: 4350,
    coverSrc: "/images/places/Meadow-View.jpg",
    date: "2022-09-02",
    type: "Hotels",
  },
  {
    id: 23,
    location: "Taipei",
    title: "Highclere",
    serviceTime: 7,
    deliveryFee: "985 Lorem ipsum dolor sit.",
    category: "dish",
    cuisine: "italian",
    rating: 3,
    price: 3300,
    coverSrc: "/images/places/Highclere.jpg",
    date: "2022-08-25",
    type: "Hotels",
  },
  {
    id: 24,
    location: "Kraków, Poland",
    title: "The Old Post Office",
    serviceTime: 10,
    deliveryFee: "1458 Lorem ipsum dolor sit.",
    category: "dish",
    cuisine: "chinese",
    rating: 2,
    price: 4100,
    coverSrc: "/images/places/The-Old-Post-Office.jpg",
    date: "2022-10-12",
    type: "Houses",
  },
];
